# @package _global_.dataset

slots:
  input:
    object: object
    scene: scene
  output:
    object: object
    scene: scene
tasks:
  - name: autoencoding
    input:
      object:
        magnitude: 1.0
      scene:
        magnitude: 1.0
    output:
      object:
        magnitude: 1.0
      scene:
        magnitude: 1.0
  - name: face_prediction
    input:
      scene:
        magnitude: 1.0
    output:
      object:
        magnitude: 1.0
  - name: scene_input
    input:
      scene:
        magnitude: 1.0
    output:
      scene:
        magnitude: 1.0
