# @package _global_
defaults:
  - /experiment_hparams: chanales2021

items:
  items:
    - name: color
      stimulus_type: circular
      n_groups: 6
      n_items: 2
      bump_width: ${experiment_hparams.bump_width}
      dim: 1152 # 64 dimensions per group
      subgroups:
        - name: ultra_sim
          distance: 6.0
        - name: high_sim
          distance: 24.0
        - name: low_sim
          distance: 72.0
    - name: face
      corr_between: ${experiment_hparams.face_corr}
      n_groups: 6
      n_items: 2
      dim: 128
      subgroups:
        - name: ultra_sim
        - name: high_sim
        - name: low_sim
    - name: object
      corr_between: 0.
      n_groups: 6
      n_items: 2
      dim: 128
      subgroups:
        - name: ultra_sim
        - name: high_sim
        - name: low_sim
