# @package _global_
defaults:
  - /experiment_hparams: favila2016

items:
  items:
    - name: scene
      corr_between: ${experiment_hparams.scene_corr_between}
      corr_within: ${experiment_hparams.scene_corr_within}
      n_groups: 6
      n_items: 2
      dim: 128
      subgroups:
        - name: no_face
        - name: different_face
        - name: same_face
    - name: face
      corr_between: ${experiment_hparams.face_corr}
      corr_within: ${experiment_hparams.face_corr}
      n_groups: 6
      n_items: 2
      dim: 128
      subgroups:
        - name: no_face
          magnitude: 0.
        - name: different_face
        - name: same_face
          corr_within: 1.
